name: 模拟测试 maomao 安装脚本

on:
  push:
    branches:
      - main

jobs:
  test-install:
    runs-on: ubuntu-latest 

    steps:
      - name: 检出项目代码
        uses: actions/checkout@v4

      # 🌟 新增的步骤：给这台虚拟机安装 Docker 和 docker-compose
      - name: 准备 Docker 环境
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          sudo systemctl start docker

      - name: 赋予脚本执行权限
        run: chmod +x install_maomao.sh

      - name: 跑起来看看会不会报错
        run: sudo ./install_maomao.sh
